"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { cn } from "./cn";

type Entry = {
  id: string;
  tier: "baked-default" | "baked-feature" | "soft-patch-reusable";
  task_canonical: string;
  what_it_does: string;
  feature_flag: string | null;
  popularity: number;
};

const TIER_LABELS: Record<Entry["tier"], string> = {
  "baked-default":       "Default for everyone",
  "baked-feature":       "Available features",
  "soft-patch-reusable": "Generated by others"
};

const TIER_ORDER: Entry["tier"][] = ["baked-feature", "soft-patch-reusable", "baked-default"];

export function LibraryTab() {
  const [entries, setEntries] = useState<Entry[]>([]);
  const [applying, setApplying] = useState<string | null>(null);
  const [loaded, setLoaded] = useState(false);
  const router = useRouter();

  useEffect(() => {
    fetch("/api/adapt/library").then(r => r.json()).then(d => {
      setEntries(d.entries || []);
      setLoaded(true);
    }).catch(() => setLoaded(true));
  }, []);

  async function apply(id: string) {
    if (applying) return;
    setApplying(id);
    try {
      await fetch(`/api/adapt/library/${id}/apply`, { method: "POST" });
      setTimeout(() => router.refresh(), 250);
    } finally {
      setApplying(null);
    }
  }

  if (!loaded) return <div className="text-sm text-ink-500">Loading library…</div>;
  if (entries.length === 0) return <div className="text-sm text-ink-500">Library is empty.</div>;

  const grouped: Record<string, Entry[]> = {};
  for (const e of entries) (grouped[e.tier] = grouped[e.tier] || []).push(e);

  return (
    <div className="space-y-5">
      {TIER_ORDER.map(tier => {
        const items = grouped[tier];
        if (!items || items.length === 0) return null;
        return (
          <section key={tier}>
            <h3 className="mb-2 text-[11px] font-medium uppercase tracking-wider text-ink-400">{TIER_LABELS[tier]}</h3>
            <ul className="space-y-2">
              {items.map(e => (
                <li key={e.id} className="flex items-start justify-between gap-3 rounded-lg border border-ink-200 bg-white p-3 dark:border-ink-800 dark:bg-ink-900">
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium leading-snug">{e.task_canonical}</p>
                    <p className="mt-0.5 text-[11px] text-ink-500">{e.what_it_does}</p>
                    {e.popularity > 0 && (
                      <p className="mt-1 text-[10px] text-ink-400">used {e.popularity}×</p>
                    )}
                  </div>
                  <button
                    onClick={() => apply(e.id)}
                    disabled={applying === e.id || tier === "baked-default"}
                    className={cn(
                      "rounded-md px-2.5 py-1 text-[11px] font-medium transition",
                      tier === "baked-default"
                        ? "bg-ink-100 text-ink-400 cursor-not-allowed dark:bg-ink-800"
                        : "bg-ink-900 text-ink-50 hover:bg-ink-800 dark:bg-ink-100 dark:text-ink-900 dark:hover:bg-ink-200"
                    )}
                  >
                    {tier === "baked-default" ? "Default" : applying === e.id ? "…" : "Apply"}
                  </button>
                </li>
              ))}
            </ul>
          </section>
        );
      })}
    </div>
  );
}
